### ISSUE TITLE
2.0.8 Linux crashes on start..

### ISSUE THREAD

**Issue by scruffynerf** [0x90d/videoduplicatefinder#103]
Linux - Ubuntu 16.04

Previous version worked
new 2.0.8 crashes:

```
$ ./VideoDuplicateFinderLinux

Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for VideoDuplicateFinderLinux.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at VideoDuplicateFinderLinux.App.Initialize() in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\Program.cs:line 7
Aborted (core dumped)
```

**Comment by scruffynerf** [comment]
related?:

https://github.com/AvaloniaUI/Avalonia/issues/3383

**Comment by G-R-A-F-F** [comment]
same issue here.
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-42-generic

Not sure how to apply knowledge from the thread that **scruffynerf** is referring to.

**Comment by wallace11** [comment]
Same issue here with Arch Linux.

**Comment by rpatterson** [comment]
Same here.  I'd love to help with debugging, is there any way I can provide more context?

In the meantime, I tried downgrading to `2.0.7` but it just segfaults right away:

```
$ /usr/local/src/VDF.Linux-x64/VideoDuplicateFinderLinux
Segmentation fault (core dumped)
```

Tailing logs gives a little more:

```
$ tail -F /var/log/*log
==> /var/log/syslog <==
Nov 22 12:04:31 library kernel: [184717.317625] VideoDuplicateF[1225813]: segfault at ffffffffffffff48 ip 00007ffabd47e804 sp 00007ffc274c8c10 error 5 in libSkiaSharp.so[7ffabd1ae000+94d000]
Nov 22 12:04:31 library kernel: [184717.317630] Code: ff ff eb e8 bb ff ff ff ff eb d7 66 2e 0f 1f 84 00 00 00 00 00 90 41 57 41 56 41 55 41 54 55 53 48 89 f5 48 89 fb 48 83 ec 18 <0f> b6 45 00 3c 20 0f 84 4b 01 00 00 84 c0 0f 84 a8 01 00 00 48 8d

==> /var/log/kern.log <==
Nov 22 12:04:31 library kernel: [184717.317625] VideoDuplicateF[1225813]: segfault at ffffffffffffff48 ip 00007ffabd47e804 sp 00007ffc274c8c10 error 5 in libSkiaSharp.so[7ffabd1ae000+94d000]
Nov 22 12:04:31 library kernel: [184717.317630] Code: ff ff eb e8 bb ff ff ff ff eb d7 66 2e 0f 1f 84 00 00 00 00 00 90 41 57 41 56 41 55 41 54 55 53 48 89 f5 48 89 fb 48 83 ec 18 <0f> b6 45 00 3c 20 0f 84 4b 01 00 00 84 c0 0f 84 a8 01 00 00 48 8d

==> /var/log/apport.log <==
ERROR: apport (pid 1225823) Sun Nov 22 12:04:31 2020: called for pid 1225813, signal 11, core limit 0, dump mode 1
ERROR: apport (pid 1225823) Sun Nov 22 12:04:31 2020: executable: /usr/local/src/VDF.Linux-x64/VideoDuplicateFinderLinux (command line "/usr/local/src/VDF.Linux-x64/VideoDuplicateFinderLinux")
ERROR: apport (pid 1225823) Sun Nov 22 12:04:31 2020: executable does not belong to a package, ignoring
```

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2

**Comment by kopf** [comment]
@0x90d - Hi there, where can we find a newer version? The releases - https://github.com/0x90d/videoduplicatefinder/releases - still list 2.0.8 as the latest release, and the "latest build" link in the README - https://ci.appveyor.com/project/0x90d/videoduplicatefinder/branch/master/artifacts - doesn't contain any artifacts.
