### ISSUE TITLE
Exception during scan

### ISSUE THREAD

**Issue by smares** [0x90d/videoduplicatefinder#108]
**Environment**
 - OS: Windows 10

**Describe the bug**
During the scan, I am getting the following exception (replaced the actual file path with "<path to m4v file>".

```
---------------------------
CurrentDispatcher.UnhandledException
---------------------------
System.AggregateException: One or more errors occurred. ('<path to m4v file>' ffmpeg timed out on retrieving thumbnail)

 ---> System.TimeoutException: '<path to m4v file>' ffmpeg timed out on retrieving thumbnail

   at DuplicateFinderEngine.FFmpegWrapper.FFmpegWrapper.RunFFmpeg(String input, FFmpegSettings settings) in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\FFmpegWrapper\FFmpegWrapper.cs:line 73

   at DuplicateFinderEngine.FFmpegWrapper.FFmpegWrapper.GetVideoThumbnail(String inputFile, Single frameTime, Boolean grayScale) in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\FFmpegWrapper\FFmpegWrapper.cs:line 20

   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnailAsBitmaps(FileEntry videoFile, List`1 positions) in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 368

   at DuplicateFinderEngine.ScanEngine.<>c__DisplayClass49_1.<InternalSearch>b__2(Int32 i) in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 201

   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)

   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)

   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)

   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)

   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)

   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)

   at DuplicateFinderEngine.ScanEngine.InternalSearch(CancellationToken cancelToken, PauseTokenSource pauseTokenSource) in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 210

   at DuplicateFinderEngine.ScanEngine.<StartSearch>b__35_0() in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 63

   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location where exception was thrown ---

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

--- End of stack trace from previous location where exception was thrown ---

   at DuplicateFinderEngine.ScanEngine.StartSearch() in C:\Users\User\Desktop\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 64

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

**Expected behavior**
The scan finishes and shows duplicates (if any)

**Comment by smares** [comment]
It's always a different file by the way and sometimes it happens right away, sometimes after hundreds of files have been scanned.

**Comment by 85256638** [comment]
I am having the same issue

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
