### ISSUE TITLE
Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by AccaGihu** [0x90d/videoduplicatefinder#111]
**Environment**
 - OS: x86_64 Linux 5.8.11-1-MANJARO 

**Describe the bug**
The program crashes when enumerating

`Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at ProtoBuf.ProtoReader.TryReadUInt32VariantWithoutMoving(Boolean trimNegative, UInt32& value) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 140
   at ProtoBuf.ProtoReader.TryReadUInt32Variant(UInt32& value) in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 200
   at ProtoBuf.ProtoReader.ReadFieldHeader() in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 658
   at ProtoBuf.ProtoReader.SkipField() in C:\code\protobuf-net\src\protobuf-net\ProtoReader.cs:line 783
   at ProtoBuf.Meta.TypeModel.TryDeserializeAuxiliaryType(ProtoReader reader, DataFormat format, Int32 tag, Type type, Object& value, Boolean skipOtherFields, Boolean asListItem, Boolean autoCreate, Boolean insideList, Object parentListOrType) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 1121
   at ProtoBuf.Meta.TypeModel.TryDeserializeList(TypeModel model, ProtoReader reader, DataFormat format, Int32 tag, Type listType, Type itemType, Object& value) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 946
   at ProtoBuf.Meta.TypeModel.TryDeserializeAuxiliaryType(ProtoReader reader, DataFormat format, Int32 tag, Type type, Object& value, Boolean skipOtherFields, Boolean asListItem, Boolean autoCreate, Boolean insideList, Object parentListOrType) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 1093
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 722
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 591
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 570
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in C:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 68
   at DuplicateFinderEngine.DatabaseHelper.LoadDatabase() in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\DatabaseHelper.cs:line 29
   at DuplicateFinderEngine.ScanEngine.InternalBuildFileList() in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 90
   at DuplicateFinderEngine.ScanEngine.<StartSearch>b__35_0() in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 52
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at DuplicateFinderEngine.ScanEngine.StartSearch() in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__142_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by AccaGihu** [comment]
Somehow deleting Settings.xml resolved the issue

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
