### ISSUE TITLE
TaskScheduler.UnobservedTaskException during scan

### ISSUE THREAD

**Issue by smares** [0x90d/videoduplicatefinder#119]
**Environment**
 - OS: Windows 10

**Describe the bug**
The following error appears during scan:

```
---------------------------
TaskScheduler.UnobservedTaskException
---------------------------
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a closed Stream.)

 ---> System.ObjectDisposedException: Cannot access a closed Stream.

   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)

   at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---
---------------------------
OK   
---------------------------
```

The scan is working in the background and the program eventually finishes the scan successfully. The error is sometimes thrown multiple times.

**Expected behavior**
No error during scan

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
