### ISSUE TITLE
How to open the software on Linux?

### ISSUE THREAD

**Issue by oliveox** [0x90d/videoduplicatefinder#129]
**Environment**
 - OS: Linux (Ubuntu 20.4)

**Describe the bug**
I've installed all the dependencies. Not a debug per see but I couldn't find any way to open the software on my Linux distro after decompressing the VDF.Linux-x64.tar.gz file from the release assets. Contrary to the windows release where I intuitively opened the software using the .exe file, I didn't find any .sh for the Linux release.

**Expected behavior**
I suggest adding a short docs explanation about how to open the software on Linux (maybe Windows too).

P.S.
Other than that, great work, thank you!

**Comment by Maltragor** [comment]
The executables are "VideoDuplicateFinderLinux" (GUI) and  "VideoDuplicateFinderConsole".
But most likely you will not be able to run it or it will not work properly. If you run VideoDuplicateFinderLinux from terminal you will see the error messages.

Depending issues:
#104, #103, #94, #65, #64, ...

I use Linux Mint and only got version 2.0.7 to run under the old linuxmint-19-cinnamon-64bit-v2.iso. 
No luck on newer linux versions.
To solve the no thumbnail problem, also install libc6-dev. Which unfortunately helps at least with me only in older linux versions.

**Comment by sergiotca** [comment]
I just stumble on this project so please forgive me If this is a stupid question.
From what I got from the issues forum, there is currently no way to run this on Linux, right?
Is the project even still maintained? I see no official updates on the code in months.

**Comment by eGit** [comment]
The UI works with version 2.0.7 on Linux. Thumbnails don't despite libc6-dev.

HOWEVER: even with the newest version on the console I get a strange result. I want it to find two videos of same size in seconds. Everything else could be differen. Resolution, codec, etc.

However it tells me it finds no duplicates (Percent: 100%) or it detects ALL videos as duplicates (99% and less). This is all so confusing. Also on the console.

Is it different on Windows? Does it detect correctly on Windows?

Seems like Linux is not supported. Why not remove it then instead of wasting peoples time?!

**Comment by Maltragor** [comment]
I also noticed the problem that everything is recognized as a duplicate with my current Linux versions.
I assume that the reason is related to the thumbnail issue.
Conjecture:
- Single images are created internally to compare the videos
- If there are also problems here like with the thumbnails, all these images would be the same (so e.g. black or white depending on the initialization)

Notice: The software creates a database of the scanned videos in order to work faster in subsequent runs. So if the database is created with incorrect images a subsequent change on the Linux installation would not effect the scan result. And I'm not sure if the database delete button really worked. But at least if the path or filename of the videos change, the files are completely rescanned.
Sorry, I had not really tried to investigate and reproduce the phenomena but only wanted to come to a solution acceptable to me at that time. And using VMWare to run linuxmint-19-cinnamon-64bit-v2.iso in combination with a bash script installing all the missing packages has been enough for me to use it once every few months / a year.

So in principle the software work(s/ed) very well, even under Linux.
Unfortunately, however, there were apparently changes to several Linux libraries some time ago, so that is currently no longer the case. 

As sergiotca mentioned the last update was already quite a while ago (and also I would be interested if the project is still maintained).

@eGit: 
Nobody forces you to use (this) open source software ;-)
If you know a better video duplicate search tool running under Linux you can use it (and please tell me the name of the software).
(And assumed the project is not maintained any longer / at the moment, who should remove anything? And at least version 2.0.7 is working with older libraries as expected.)

**Comment by oliveox** [comment]
> Sorry, I had not really tried to investigate and reproduce the phenomena but only wanted to come to a solution acceptable to me at that time. And using VMWare to run linuxmint-19-cinnamon-64bit-v2.iso in combination with a bash script installing all the missing packages has been enough for me to use it once every few months / a year.


Could you share with us the bash script you are talking about?

**Comment by Maltragor** [comment]
The reason for the bash is only because I did not want to install Linux (in the VM) but only boot the iso each time and then I did not want to manually install the missing packages each time.
But of course I can post it.

The VM has a small virtual hard disk with the bash script, the videoduplicatfinder application and the missing packages on it (so I don't have to download them every time. "./apt-cache/" is a directory on this disk)

So as you see it only installs ffmpeg, libgdiplus and libc6-dev related to the videoduplicatfinder thematic.
(In addition it installs the vm-tools and mount my shared vm folders. Furthermore I change the keyboard layout and install some other applications but this is only due to further personal requirements so I removed it here)

```bash
#!/bin/bash

sudo cp ./apt-cache/* /var/cache/apt/archives
sudo apt install -y open-vm-tools
sudo apt install -y ffmpeg
sudo apt install -y libgdiplus
sudo apt install -y libc6-dev

vmhgfs-fuse .host:/ ./vm-share

```

**Comment by mf720** [comment]
I'd love to be able to use the Software again under Linux X64 - Debian in my case.If someone is capable and willing to get it to run again in that use case and get rid of the Avalonia Errors I would be very happy and thankful. If I can make it worth your wile just drop me a line please.

The Error:
Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for VideoDuplicateFinderLinux.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at VideoDuplicateFinderLinux.App.Initialize() in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\Program.cs:line 7
Abgebrochen
"

**Comment by Maltragor** [comment]
I have noticed that @cognitivezen [forked the repository](https://github.com/cognitivezen/videoduplicatefinder/tree/develop) ([see network graph](https://github.com/0x90d/videoduplicatefinder/network)) and made some changes including to get it back to running with Ubuntu 20.10.
I could successfully build and execute it on Linux Mint 20.
First you have to [install the .NET Core SDK package](https://docs.microsoft.com/de-de/dotnet/core/install/linux).
Then run `dotnet publish -c Release -v q --self-contained -r linux-x64 -o "..\Releases\VDF.Linux-x64"` inside the VideoDuplicateFinderLinux subdirectory.


Annotations:

cognitivezen fork uses .net 5 since his last commits. 
The file manager Nemo/Nautilus seems to have a problem recognizing the the correct file type of .net 5 executables, so the files are classified as "(application/x-sharedlib)" instead of "(application/x-executable)" and will not be executed by double click.
This is also mentioned [here](https://github.com/dotnet/runtime/issues/42501).
But you can run it from command line or create a starter (.desktop file) to execute it.

Videoduplicatefinder creates a database of scanned files inside its binary directory. (ScannedFiles.db)
It could help to delete (/rename) this file if the scan result is not as expected. (The "Cleanup Database" does not have this effect because it does not delete the file / all entries). At least I had the problem with wrong results after the database was created with a not correct working version of the program.

**Comment by mf720** [comment]
Thank you, I'll try that out.

**Comment by mf720** [comment]
> Thank you, I'll try that out.

Tried that out, worked. Thank You + all the best @Maltragor

**Comment by matthewstrasiotto** [comment]
I have a working build that I've now got running against up-to-date avalonia in my fork https://github.com/matthewstrasiotto/videoduplicatefinder
