### ISSUE TITLE
Could someone possibly compile a MacOS version? I would PAY THEM.

### ISSUE THREAD

**Issue by speedheathenULTRA** [0x90d/videoduplicatefinder#130]
Would love to be able to run this native in MacOS instead of Parallels, even maxed out on a HighPoint 8TB RAID 0 it's still taking forever to churn through 14TB's of video.

I'd be happy to pay someone to code a MacOS version!

**Comment by Thefrank** [comment]
the console part should build without issue as long as you have the SDK. this was built using dotnet 3.1.11 under FreeBSD and targetting osx-x64. I do not have a mac to test it on but it `file` seems to return the right amount of information:
`VDF.OSX-x64/VideoDuplicateFinderConsole: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>`

https://mega.nz/file/pUh2XAII#WhHtx-YWufcNWDyE9_Xx4SuYpRarYsq3NEp5Z7AmAao

**Comment by vsolina2** [comment]
after installing dotnet for OSX https://dotnet.microsoft.com/download/dotnet/5.0
 and getting quite a few security warnings regarding unknown developer finally appears to function I will have to test it later

**Comment by Thefrank** [comment]
if you are using my build then it should run without the needs for dotnet as it was built as "stand alone". if you are building it then it will needs atleast dotnet 3.1 or higher. NuGet will grab anything missing to build the console part

**Comment by vsolina2** [comment]
I had a message in terminal that I needed to install it

**Comment by Thefrank** [comment]
100% a YOLO build for the GUI:
https://mega.nz/file/EIoyWK7a#NYqhufu86LIpcKBL50cL6Wpd8db8QySNOPweEj5joL8

yes, it still says Linux. I did not think it would even build on first go. If it works I will be shocked.

**Comment by speedheathenULTRA** [comment]
> 100% a YOLO build for the GUI:
> https://mega.nz/file/EIoyWK7a#NYqhufu86LIpcKBL50cL6Wpd8db8QySNOPweEj5joL8
> 
> yes, it still says Linux. I did not think it would even build on first go. If it works I will be shocked.

WOW! Thanks for trying guys!! When I download the package and try to run VideoDuplicateFinderLinux I get this:

Last login: Mon Mar  8 03:37:17 on ttys004
/Users/heathenadmin/Downloads/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
HEATHEN-HackPro-51:~ heathenadmin$ /Users/heathenadmin/Downloads/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for VideoDuplicateFinderLinux.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at VideoDuplicateFinderLinux.App.Initialize() in /root/videoduplicatefinder/VideoDuplicateFinderLinux/App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in /root/videoduplicatefinder/VideoDuplicateFinderLinux/Program.cs:line 7
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Thefrank** [comment]
it looks like its missing an `x:Class` so that will require "actual coding" from me. I will look at it tomorrow when I wake up

**Comment by speedheathenULTRA** [comment]
> it looks like its missing an `x:Class` so that will require "actual coding" from me. I will look at it tomorrow when I wake up
> 
> edit: should also fix linux builds too if I can ever get it work
> 
> btw does console work ok atleast?

You're awesome Frank, thank you!!!

**Comment by vsolina2** [comment]
Yes Thank you also

**Comment by Thefrank** [comment]
If the console version is working I suggest using it if you NEED something ASAP.
From what I recall it does not do any of the actual deleting/moving/ignoring; it just generates an html file with screenshots and a few details of the dupes it found (res, file size, codecs, length)

**Comment by Thefrank** [comment]
https://mega.nz/file/FdxUDJTK#_S5BPydreMPKd9EW8EliP9ItNgBkPu-xeaFetrDtTXE

added what I think it needs and it builds. I have no idea if this will work because I dont have a Linux box with GUI or OSX box and these errors seem to only be caught at runtime and not buildtime annoying me to no end.

**Comment by vsolina2** [comment]
New results for GUI version
Thank yo again for your efforts

/Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;                  
vs@AAiMac-2 ~ % /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Marvin' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'System.Security.Cryptography.Native.Apple' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSystem.Security.Cryptography.Native.Apple, 1): image not found
   at Interop.AppleCrypto.AppleCryptoNative_GetRandomBytes(Byte* buf, Int32 num, Int32& errorCode)
   at Interop.AppleCrypto.GetRandomBytes(Byte* pbBuffer, Int32 count)
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte* pbBuffer, Int32 count)
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Span`1 data)
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte[] data)
   at System.Marvin.GenerateSeed()
   at System.Marvin..cctor()
   --- End of inner exception stack trace ---
   at System.Marvin.get_DefaultSeed()
   at System.Xml.NameTable.ComputeHash32(String key)
   at System.Xml.NameTable.Add(String key)
   at System.Xml.XmlNamespaceManager..ctor(XmlNameTable nameTable)
   at System.Xml.XmlTextReaderImpl..ctor(XmlResolver resolver, XmlReaderSettings settings, XmlParserContext context)
   at System.Xml.XmlTextReaderImpl..ctor(Stream stream, Byte[] bytes, Int32 byteCount, XmlReaderSettings settings, Uri baseUri, String baseUriStr, XmlParserContext context, Boolean closeInput)
   at System.Xml.XmlReaderSettings.CreateReader(Stream input, Uri baseUri, String baseUriString, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(Stream input, XmlReaderSettings settings, String baseUri)
   at System.Xml.XmlReader.Create(Stream input, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream)
   at Avalonia.Utilities.AvaloniaResourcesIndexReaderWriter.Read(Stream stream)
   at Avalonia.Shared.PlatformSupport.AssetLoader.AssemblyDescriptor..ctor(Assembly assembly)
   at Avalonia.Shared.PlatformSupport.AssetLoader..ctor(Assembly assembly)
   at Avalonia.Shared.PlatformSupport.StandardRuntimePlatformServices.Register(Assembly assembly)
   at Avalonia.AppBuilder.<>c.<.ctor>b__0_0(AppBuilder builder)
   at Avalonia.Controls.AppBuilderBase`1.<>c__DisplayClass44_0.<.ctor>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in /root/videoduplicatefinder/VideoDuplicateFinderLinux/Program.cs:line 7
zsh: abort      /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Thefrank** [comment]
do you have openssl installed? I think that is the error for it being missing on OSX

**Comment by vsolina2** [comment]
Fewer lines

'''/Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;                  
vs@AAiMac-2 ~ % /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libAvaloniaNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibAvaloniaNative, 1): image not found
   at Avalonia.Native.AvaloniaNativePlatform.CreateAvaloniaNative()
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in /root/videoduplicatefinder/VideoDuplicateFinderLinux/Program.cs:line 7
zsh: abort      /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]
'''

**Comment by Thefrank** [comment]
stupid/bad idea:
try renaming `libAvaloniaNative.dylib` to `liblibAvaloniaNative` (as with the double lib thing and no extension). I think some of this comes from it not being built natively under xcode and dotnet guessing but im not sure

**Comment by vsolina2** [comment]
Improvement ?
```
/Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;                  
vs@AAiMac-2 ~ % /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
Error:
  An assembly specified in the application dependencies manifest (VideoDuplicateFinderLinux.deps.json) was not found:
    package: 'Avalonia.Native', version: '0.9.10'
    path: 'runtimes/osx/native/libAvaloniaNative.dylib'
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]



```

**Comment by Thefrank** [comment]
did you rename it or make a symlink? if you renamed it, revert the rename and use a symlink instead.

**Comment by vsolina2** [comment]
I renamed it this is after a symlink
```/Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux ; exit;
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Themes.Default.DefaultTheme.xaml, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Avalonia.Themes.Default.DefaultTheme.xaml, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(String name)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetResAsmAndPath(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri)
   at Avalonia.Shared.PlatformSupport.AssetLoader.GetAssembly(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri)
   at Avalonia.Markup.Xaml.Styling.StyleInclude.get_Loaded()
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.ISetResourceParent.ParentResourcesChanged(ResourcesChangedEventArgs e)
   at Avalonia.Styling.Styles.<.ctor>b__4_0(IStyle x)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass0_0`1.<ForEachItem>b__0(Int32 _, T i)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>g__Add|0(Int32 index, IList items)
   at Avalonia.Collections.AvaloniaListExtensions.<>c__DisplayClass1_0`1.<ForEachItem>b__2(Object _, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)
   at Avalonia.Collections.AvaloniaList`1.Add(T item)
   at Avalonia.Styling.Styles.Add(IStyle item)
   at VideoDuplicateFinderLinux.App.!XamlIlPopulate(IServiceProvider , App ) in VideoDuplicateFinderLinux.App.xaml:line 7
   at VideoDuplicateFinderLinux.App.!XamlIlPopulateTrampoline(App )
   at VideoDuplicateFinderLinux.App.Initialize() in /root/videoduplicatefinder/VideoDuplicateFinderLinux/App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in /root/videoduplicatefinder/VideoDuplicateFinderLinux/Program.cs:line 7


zsh: abort      /Applications/VDFGUI.OSX-x64/VideoDuplicateFinderLinux
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by Thefrank** [comment]
That file is not a part of what was built or a part of the original code. It should be provided by or contained in `Avalonia.Themes.Default` which in this case is `Avalonia.Themes.Default.dll` which is a windows file format not an osx file. In most cases this is not an issue (both Linux and FreeBSD binaries built with dotnet don't really care) so im not quite sure what is going on. I will try one more thing

**Comment by vsolina2** [comment]
the result 
```
/Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;             
vs@AAiMac-2 ~ % /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;
Failed to load a, error: dlopen(/Applications/VDFGui.OSX-x64-test/libcoreclr.dylib, 1): no suitable image found.  Did find:
	/Applications/VDFGui.OSX-x64-test/libcoreclr.dylib: code signature in (/Applications/VDFGui.OSX-x64-test/libcoreclr.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
Failed to bind to CoreCLR at '/Applications/VDFGui.OSX-x64-test/'
Failed to create CoreCLR, HRESULT: 0x80008088
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]




```

**Comment by Thefrank** [comment]
that looks like a gatekeeper/quarantine issue from what google says. Is there someway to disable/bypass that?

**Comment by vsolina2** [comment]
results in 2 versions seemingly random asnd as for security OSX likes to give the screen ilke this on many files mainly to to unidentified developer
<img width="597" alt="Screen Shot 2021-03-10 at 12 22 03 pm" src="https://user-images.githubusercontent.com/64821096/110561556-ff6a4280-819b-11eb-8ffa-764ca8a2ee41.png">

```/Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;             
vs@AAiMac-2 ~ % /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;
zsh: segmentation fault  /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]


```
or

```/Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;
vs@AAiMac-2 ~ % /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libAvaloniaNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibAvaloniaNative, 1): image not found
   at Avalonia.Native.AvaloniaNativePlatform.CreateAvaloniaNative()
   at Avalonia.Native.AvaloniaNativePlatform.Initialize(AvaloniaNativePlatformOptions options)
   at Avalonia.AvaloniaNativePlatformExtensions.<>c__DisplayClass0_0`1.<UseAvaloniaNative>b__0()
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in /root/videoduplicatefinder/VideoDuplicateFinderLinux/Program.cs:line 7
zsh: abort      /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by Thefrank** [comment]
that first error does not provide any more details about what caused it to seg fault :(
that second error might be resolvable by making the same/similar symlink as before

**Comment by vsolina2** [comment]
Sorry it took a while to get back to this the result after a Symlink
'''Last login: Wed Mar 17 09:38:37 on ttys005
/Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;             
vs@AAiMac-2 ~ % /Applications/VDFGui.OSX-x64-test/VideoDuplicateFinderLinux ; exit;

'''
Its actually running a process and a Menu title no menu items or app window trying to close the terminal results in do you want to close while a process is running
<img width="278" alt="Screen Shot 2021-03-17 at 9 45 28 am" src="https://user-images.githubusercontent.com/64821096/111389758-a2274180-8705-11eb-8c16-36d363b7110f.png">
<img width="627" alt="Screen Shot 2021-03-17 at 9 44 21 am" src="https://user-images.githubusercontent.com/64821096/111389765-a4899b80-8705-11eb-8182-529ca130c953.png">

**Comment by Thefrank** [comment]
It looks like the linux UI cant be easily dropped over to OSX. I have no experience with Avalonia (no UI experience at all actually) so this is likely something that the main dev or someone with more UI experience will have to deal with :(

@speedheathenULTRA pinging you for this too. You can try some of those "code bounty" forums and you will likely get a better/faster response than an issue on GH :)

**Comment by matthewstrasiotto** [comment]
So, this project appears mostly abandoned for quite a few months, but I've put in an PR  ( #136 ) that lets the console app output to json instead of HTML. The upshot? We should be able to start building tools that don't rely on .NET to deal with this.

I'll probably write some sort of webservice wrapper for this, & then some kind of webapp that lets you do this in browser, since I personally need this for a remote media server.

**Comment by speedheathenULTRA** [comment]
@matthewstrasiotto please keep me posted on that!!

**Comment by matthewstrasiotto** [comment]
Will do - I'll gladly accept your money for the project, by the way!

**Comment by FatalFallacy** [comment]
I managed to successfully build console and GUI for MacOS locally by:

- building and installing the Avalonia MacOS native libraries as described here: [https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md](url)

- applying @cognitivezen 's patch for the Linux UI build for 'Avalonia 0.9.12 with Ubuntu 20.10' issue: [https://github.com/cognitivezen/videoduplicatefinder/commit/994efac3463e20e7319ac5edfbb1440a59d3bdf4](url),

- together with input from @fixmk pull request for the MacOS console build: [https://github.com/0x90d/videoduplicatefinder/pull/132/commits
](url)
 
With that I am able to build both MacOS console and GUI app for VDF with following build script:

```bash
#/bin/bash

cd VideoDuplicateFinder.Console &&
dotnet publish -c Release -v q --self-contained -r osx.10.15-x64 -o "..\Releases\VDF.OSX-x64" &&
cd -

cd VideoDuplicateFinderLinux &&
dotnet publish -c Release -v q --self-contained -r osx.10.15-x64  -f netcoreapp3.1 -o "..\Releases\VDF.OSX-x64" &&
cd -
```
VDF running under MacOS Mojave here, fired from terminal:
```console
mbp:VDF.OSX-x64 ff$ pwd
/Users/ff/projects/videoduplicatefinder/Releases/VDF.OSX-x64
mbp:VDF.OSX-x64 ff$ ./VideoDuplicateFinderLinux
```
Screenshot:
![Bildschirmfoto 2021-07-26 um 13 44 05](https://user-images.githubusercontent.com/6464031/126983789-567f85a9-929d-4013-9d45-8397b18f07f7.png)

**Comment by speedheathenULTRA** [comment]
@FatalFallacy hit me, jason@speedheathens.com will $$$ for a packaged install to run on BigSur

**Comment by vsolina2** [comment]
https://github.com/matthewstrasiotto/videoduplicatefinder/releases/tag/v2.1.0

you may want to see link and offer Mathew some $$$ he has made good progress so far

**Comment by speedheathenULTRA** [comment]
@vsolina2 I will. I emailed him. I need to have someone package this up so I can install it. Just waiting to hear back from him. @FatalFallacy HMU.

**Comment by matthewstrasiotto** [comment]
@speedheathenULTRA , by packaged install do you mean DMG / something that can be run from an icon in the applications folder?
At the moment my releases package zips with runnable binaries, so like... the app runs.

**Comment by matthewstrasiotto** [comment]
@speedheathenULTRA https://github.com/matthewstrasiotto/videoduplicatefinder/releases/tag/v2.1.0

**Comment by matthewstrasiotto** [comment]
@speedheathenULTRA 
> @vsolina2 I will. I emailed him.

I haven't yet seen the email

**Comment by speedheathenULTRA** [comment]
> @speedheathenULTRA https://github.com/matthewstrasiotto/videoduplicatefinder/releases/tag/v2.1.0

@matthewstrasiotto email me, bud jason@speedheathens.com I'll pay you to package it or walk me through setting it up.

**Comment by vsolina2** [comment]
the problem might be this:-



 just tried running it on my Mac

**Comment by vsolina2** [comment]
using the option ctrl-click open to bypass this doesn’t work as its not an application according to finder

**Comment by matthewstrasiotto** [comment]
Documented the process here: 
https://github.com/matthewstrasiotto/videoduplicatefinder/issues/28
