### ISSUE TITLE
GUI Crash after hitting Start

### ISSUE THREAD

**Issue by wallace11** [0x90d/videoduplicatefinder#147]
**Environment**
 - OS: Linux

**Describe the bug**
Running `VDF.GUI` works fine, but when hitting "Start" it crashes with the following message:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The type initializer for 'Gdip' threw an exception.) (The type initializer for 'Gdip' threw an exception.) (The type initializer for 'Gdip' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor() in System.Drawing.Common.dll:token 0x6000a7c+0x4a
   --- End of inner exception stack trace ---
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream) in System.Drawing.Common.dll:token 0x6000299+0x17
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0x1e7
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) in System.Threading.Tasks.Parallel.dll:token 0x60000be+0x5b
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x600002a+0x144
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) in System.Threading.Tasks.Parallel.dll:token 0x6000045+0xd
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x600002a+0x186
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body) in System.Threading.Tasks.Parallel.dll:token 0x600001e+0x1c
   at VDF.Core.ScanEngine.<RetrieveThumbnails>b__49_0() in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 280
   at System.Threading.Tasks.Task.InnerInvoke() in System.Private.CoreLib.dll:token 0x6002cff+0xf
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in System.Private.CoreLib.dll:token 0x6002da4+0x0
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x600296a+0x15
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x600296a+0x46
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x6002cfe+0xa5
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.RetrieveThumbnails() in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 277
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state) in System.Private.CoreLib.dll:token 0x6002da0+0x0
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at VDF.GUI.Program.Main(String[] args) in /tmp/videoduplicatefinder/VDF.GUI/Program.cs:line 27
```

**Comment by Maltragor** [comment]
> `---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies.`

Do you have installed libgdiplus?
See README.md, Requirements:
>Install latest ffmpeg and ffprobe the usual way and verify PATH environment variable is set. Also make sure you got libgdiplus installed.
>
> sudo apt-get update
> sudo apt-get install ffmpeg
> sudo apt-get install libgdiplus

**Comment by wallace11** [comment]
Hey,
I've indeed missed that part. Shame on me.
I installed it, and I still get a crash but with a different error :smile: 

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Parameter is not valid.) (Parameter is not valid.) (Parameter is not valid.)
 ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in System.Drawing.Common.dll:token 0x6000a83+0x3
   at System.Drawing.Image.InitializeFromStream(Stream stream) in System.Drawing.Common.dll:token 0x6000299+0x49
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0x1e7
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) in System.Threading.Tasks.Parallel.dll:token 0x60000be+0x5b
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x600002a+0x144
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) in System.Threading.Tasks.Parallel.dll:token 0x6000045+0xd
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x600002a+0x186
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body) in System.Threading.Tasks.Parallel.dll:token 0x600001e+0x1c
   at VDF.Core.ScanEngine.<RetrieveThumbnails>b__49_0() in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 280
   at System.Threading.Tasks.Task.InnerInvoke() in System.Private.CoreLib.dll:token 0x6002cff+0xf
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in System.Private.CoreLib.dll:token 0x6002da4+0x0
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x600296a+0x15
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x600296a+0x46
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x6002cfe+0xa5
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.RetrieveThumbnails() in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 277
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state) in System.Private.CoreLib.dll:token 0x6002da0+0x0
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at VDF.GUI.Program.Main(String[] args) in /tmp/videoduplicatefinder/VDF.GUI/Program.cs:line 27
 ---> (Inner Exception #1) System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in System.Drawing.Common.dll:token 0x6000a83+0x3
   at System.Drawing.Image.InitializeFromStream(Stream stream) in System.Drawing.Common.dll:token 0x6000299+0x49
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0x1e7
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #2) System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in System.Drawing.Common.dll:token 0x6000a83+0x3
   at System.Drawing.Image.InitializeFromStream(Stream stream) in System.Drawing.Common.dll:token 0x6000299+0x49
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0x1e7
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---
```

**Comment by Maltragor** [comment]
Hi,
first of all, I don't have a concrete solution, just a few comments.

Does the error always occur, so with all files, or only with certain ones?
As I see it, a thumbnail is created with ffmpeg, the raw data should then be loaded as an Image with Image.FromStream(). And something goes wrong in the process.

>    at System.Drawing.Image.InitializeFromStream(Stream stream) in System.Drawing.Common.dll:token 0x6000299+0x49
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive) in System.Drawing.Common.dll:token 0x6000294+0xe
>   at VDF.Core.ScanEngine.<>c__DisplayClass49_0.<RetrieveThumbnails>b__2(Int32 i) in /tmp/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 321

```c#
var b = FfmpegEngine.GetThumbnail(new FfmpegSettings {
	File = entry.Path,
	Position = TimeSpan.FromSeconds(entry.Duration.TotalSeconds * positionList[j]),
	GrayScale = 0,
});
if (b == null || b.Length == 0) return;
using var byteStream = new MemoryStream(b);          // <<< (Line 321)
var bitmapImage = Image.FromStream(byteStream);      // <<<
list.Add(bitmapImage);
```


If it concerns only single files and you want to do your own search:

The called ffmpeg command in the original is for example:
`/usr/bin/ffmpeg -hide_banner -loglevel panic -y -ss 00:11:46 -i "VideoFile.mp4" -t 1 -f mjpeg -vframes 1 -vf scale=100:-1 "-"`
The given timestamp (here 00:11:46) depends on the video and the selected number of thumbnails. In the example, the optionally selectable hardware acceleration is not used.
If you want to create the thumbnail manually, you should modify the command slightly: Output to a file instead of a stream and enable more logging output:
`/usr/bin/ffmpeg -hide_banner -ss 00:11:46 -i "VideoFile.mp4" -t 1 -f mjpeg -vframes 1 -vf scale=100:-1 /tmp/img.jpg`
(So the generated image will be saved in /tmp as img.jpg)

With a small change in FfmpegEngine.cs you can e.g. display the ffmpeg command line for all files:
```c#
Console.WriteLine($"GetThumbnail: {FFmpegPath}" + $" -hide_banner -loglevel panic -y {(UseCuda ? "-hwaccel cuda" : string.Empty)} -ss {settings.Position} -i \"{settings. File}\" -t 1 -f {(settings.GrayScale == 1 ? "rawvideo -pix_fmt gray" : "mjpeg")} -vframes 1 {(settings.GrayScale == 1 ? "-s 16x16" : "-vf scale=100:-1")} \"-\"");
```
Which could be inserted in GetThumbnail function, e.g. after line 37. 

The last output before the exception would be the problematic file and you could generate the image with the (modified) command to see what ffmpeg does.

@0x90d Shouldn't the exception handling around the thumbnails (grayscale and color) be extended a bit in general? Also for v2 there were reports that there were crashes due to unhandled exceptions. So you could log the affected file and the ffmpeg command for analysis purposes.

**Comment by wallace11** [comment]
@Maltragor 
Thanks to your awesome explanation I was able to find out that `FFmpegPath` actually resulves to `/sbin/ffmpegthumbnailer` when ffmpegthumbnailer is installed!
When I removed it, the path changed to `/sbin/ffmpeg` and the program worked as expected.

I didn't go as far as investigating why that happens but using ffmpegthumbnailer instead of ffmpeg should be done with different parameters. Or maybe just fix that ffmpeg detection and/or add an option to override ffmpeg location :)

**Comment by Maltragor** [comment]
I would guess:

FFToolsUtils.cs, GetPath(), Line 52

```c#
var files = new DirectoryInfo(path).GetFiles(tool == FFTool.FFmpeg ? $"{FFmpegExecutableName}*" : $"{FFprobeExecutableName}*", new EnumerationOptions {
```
There is a star wildcard after FFmpegExecutableName (="ffmpeg") and FFprobeExecutableName.

GetPath() has no exclusive linux handling.
There is a special handling for Windows and OSX and if this parts fail, the default search using the PATH variable is used.
Probably was intended that the star wildcard should ignore the ".exe".
So it seams, that this part using the PATH variable should be improved. (See also the too early return if nothing is found after the first PATH item)

_(The simple linux only workaround would be to remove the wildcards.)_

**Comment by Maltragor** [comment]
If I were you, I would also delete the ScannedFiles.db first. Because the duplicate search (based on which the .db was created) also uses ffmpeg. And since the wrong program was started here, as you found out, the stored data for the file comparison is probably not correct.

**Comment by wallace11** [comment]
@Maltragor 
Thanks for both tips.
Removing both stars from that variable assignment indeed did the work :)
