### ISSUE TITLE
Latest build crashes and exits without any error codes or messages

### ISSUE THREAD

**Issue by floydcg** [0x90d/videoduplicatefinder#154]
**Environment**
 - OS: [e.g. Windows / Linux]
 - Windows

**Describe the bug**
Scanning files with the latest build on Windows will scan several files, then crash and exit without any further notice. Its never the same file it crashes on. I've not tried on Linux yet. I've tried watching the log tab but no messages ever appear there before it crashes.

**Comment by Maltragor** [comment]
Is there also no output when you start VDF in the console window?

This branch disables parallel execution and shows (console output) which function is executed / which file is processed. Maybe it helps to find out a little more.

https://github.com/Maltragor/videoduplicatefinder/tree/develop/crash_search

**Comment by floydcg** [comment]
I'll give it a shot and see what happens

**Comment by floydcg** [comment]
crashing with the error "object reference not set to an instance of any object". both windows and linux debian. different files everytime

**Comment by floydcg** [comment]
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-develop-crash_search\videoduplicatefinder-develop-crash_search\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-develop-crash_search\videoduplicatefinder-develop-crash_search\VDF.Core\ScanEngine.cs:line 194
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) in System.Threading.Tasks.Parallel.dll:token 0x60000be+0x5b
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000043+0x187
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) in System.Threading.Tasks.Parallel.dll:token 0x6000045+0xd
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000043+0x1c8
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000036+0x4a
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body) in System.Threading.Tasks.Parallel.dll:token 0x600002d+0x1c
   at VDF.Core.ScanEngine.GatherInfos() in E:\Download Directory\2021\8\videoduplicatefinder-develop-crash_search\videoduplicatefinder-develop-crash_search\VDF.Core\ScanEngine.cs:line 175
   at System.Threading.Tasks.Task.InnerInvoke() in System.Private.CoreLib.dll:token 0x600319d+0xf
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj) in System.Private.CoreLib.dll:token 0x6003242+0x0
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002df4+0x15
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002df4+0x46
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600319c+0xa5
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.StartSearch() in E:\Download Directory\2021\8\videoduplicatefinder-develop-crash_search\videoduplicatefinder-develop-crash_search\VDF.Core\ScanEngine.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state) in System.Private.CoreLib.dll:token 0x600323e+0x0
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at VDF.GUI.Program.Main(String[] args) in E:\Download Directory\2021\8\videoduplicatefinder-develop-crash_search\videoduplicatefinder-develop-crash_search\VDF.GUI\Program.cs:line 27
Aborted (core dumped)

**Comment by Maltragor** [comment]
`FfmpegEngine.cs:line 67` is  `if (videoFile.grayBytes.ContainsKey(position))`

The only way I could spontaneously produce a NullReferenceException was by setting grayBytes to null.
But grayBytes is created by the constructor of FileEntry and should therefore never be null.
Expect maybe (?) if loaded from an older incompatible db file. If there was a old ScannedFiles.db in the directory you could rename it and try again.

I have added some additional debug code in my branch to test if grayBytes is null. If you like you can test it.
... or wait what @0x90d will say^^.

**Comment by floydcg** [comment]
I've not tried the new code yet, however I deleted the db, scanned and got no dupes at the 96% so I decreased down to 93% and attempted to rescan again, upon doing that it crashed again with the same error. if i delete the DB and start over, it will run. not sure if that helps or not but i guess its something.

**Comment by Maltragor** [comment]
OK,.. I can reproduce it and I know what is going wrong.

While I was working on a completely different place and added arbitrary directories to the search list for this purpose, I ran into a bug, which then resulted in the error you found^^

**Bug1:**
GetFilesRecursive does not filter correctly.
```c#
var files = Directory.EnumerateFiles(initial, "*", enumerationOptions)
				.Where(f => (includeImages ? AllExtensions : VideoExtensions)
				.Any(x => f.EndsWith(x, StringComparison.OrdinalIgnoreCase)));
```
In combination with `VideoExtensions = {... "vob", "ts" };`  this causes that not for e.g. **"*.ts"** is searched, but for **"*ts"**. Thus e.g. also `VDF.GUI.csproj.nuget.g.targets` fulfills the Krierium, which is certainly no video^^.

But because it is possible that even e.g. "*.mp4",... files are no valid videos, this is not the main problem but should still  be fixed.

**Main Bug:**
.. what happens is,...:
`BuildFileList` adds the non video file to the database [OK]
`GatherInfos` tries to get `MediaInfo` and `GrayBytes`. This fails as expected, `ThumbnailError` flag is set. [OK]
(`entry.mediaInfo` is set to an "empty" MediaInfo instance, so it is no longer `null`, `entry.grayBytes` is still a empty Dictionary)
Now starting a second search -> The Database was saved `entry.grayBytes` was a empty dictionary at this point. Now the Database is reloaded from file. Oops, `Serializer.Deserialize<HashSet<FileEntry>>(file)` did not load a empty dictionary as `entry.grayBytes`, instead now it is `null`.
=> `GatherInfos` calls `GetGrayBytesFromVideo` -> `videoFile.grayBytes.ContainsKey` raises the NullReferenceException.

Bugfix (considerations)
- Should a null entry.grayBytes be set to an empty dictionary while loading  the database  in order to be safe regardless of the rest of the changes?
- `ScanEngine.InvalidEntry` probably should filter entries with grayBytes == null.
- Maybe ScanEngine.InvalidEntry` should filter ThumbnailError entries

In addition the handling of invalid image files should also be considered. I have not checked whether there are any special cases.

**Comment by 0x90d** [comment]
> In combination with `VideoExtensions = {... "vob", "ts" };` this causes that not for e.g. **"*.ts"** is searched, but for **"*ts"**. Thus e.g. also `VDF.GUI.csproj.nuget.g.targets` fulfills the Krierium, which is certainly no video^^.

Good catch! I will fix this.

> In addition the handling of invalid image files should also be considered. I have not checked whether there are any special cases.

It is considered I think:
https://github.com/0x90d/videoduplicatefinder/blob/29deaa13a2ee11916d4f4b9f38100218b117a880/VDF.Core/ScanEngine.cs#L379

> * Should a null entry.grayBytes be set to an empty dictionary while loading  the database  in order to be safe regardless of the rest of the changes?

The only case where its null is from an outdated database and v3 is not ready to be used yet because there might still be changes. Reminding me to allow importing v2 database and convert it to v3.

**Comment by Maltragor** [comment]
>>Should a null entry.grayBytes be set to an empty dictionary while loading the database in order to be safe regardless of the rest of the changes?

>The only case where its null is from an outdated database and v3 is not ready to be used yet because there might still be changes. Reminding me to allow importing v2 database and convert it to v3.

Maybe my explanation was not so good, and my English could be better, I know^^. ..
But please read the "Main Bug" comments again / if necessary I can explain it in more detail.
=> Starting with an empty/not existing database -> start a search including a "corrupted" video (something not filtered by extension, but not be able to extract thumbnails from) -> Database is created -> If VDF loads this just created db again (so same program version) the grayBytes member is loaded as null and not as empty dictionary. -> VDF will always crash if a corrupted video is in your collection.
=> 'Bugfix' then describes the inconsistent handling of ThumbnailError vs. to dark error among others.

Problems with loading incompatible db versions within non released commits I wouldn't mention.

I hope you will read this, although you have already closed the issue. Otherwise I have to open a new one^^.
(You close the issues unfortunately always quite quickly ;-) )

**Comment by floydcg** [comment]
I just tried the latest "autobuild" and its infact still crashing as well. Just an FYI.

**Comment by floydcg** [comment]
Also just thought I would mention that i scanned the exact same files with v2 and it had no problems with them. But i'm NOT reusing the database from v2 for this build. This is a new DB everytime created by V3.
