### ISSUE TITLE
latest build still crashing

### ISSUE THREAD

**Issue by floydcg** [0x90d/videoduplicatefinder#162]
**Environment**
 - OS: both windows and linux

**Describe the bug**
Latest build will scan ok 1 time, but any scan afterwards crashes with the GetGrayBytesFromVideo error again.

Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure) in System.Threading.Tasks.Parallel.dll:token 0x60000be+0x5b
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000043+0x187
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException) in System.Threading.Tasks.Parallel.dll:token 0x6000045+0xd
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000043+0x1c8
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) in System.Threading.Tasks.Parallel.dll:token 0x6000036+0x4a
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body) in System.Threading.Tasks.Parallel.dll:token 0x600002d+0x1c
   at VDF.Core.ScanEngine.GatherInfos() in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 180
   at System.Threading.Tasks.Task.InnerInvoke() in System.Private.CoreLib.dll:token 0x600319d+0xf
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj) in System.Private.CoreLib.dll:token 0x6003242+0x0
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002df4+0x15
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002df4+0x46
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in System.Private.CoreLib.dll:token 0x600319c+0xa5
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.StartSearch() in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state) in System.Private.CoreLib.dll:token 0x600323e+0x0
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at VDF.GUI.Program.Main(String[] args) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.GUI\Program.cs:line 27
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #4) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #5) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #6) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #7) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #8) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #9) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #10) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #11) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

 ---> (Inner Exception #12) System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.FFTools.FfmpegEngine.GetGrayBytesFromVideo(FileEntry videoFile, List`1 positions) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\FFTools\FfmpegEngine.cs:line 67
   at VDF.Core.ScanEngine.<GatherInfos>b__50_0(FileEntry entry) in E:\Download Directory\2021\8\videoduplicatefinder-master (1)\videoduplicatefinder-master\VDF.Core\ScanEngine.cs:line 199
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x103
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000079+0x261
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x60000ce+0x0
   at System.Threading.Tasks.TaskReplicator.Replica.Execute() in System.Threading.Tasks.Parallel.dll:token 0x60000c5+0x0<---

Deleting the DB and starting over, will allow scanning again

**Comment by floydcg** [comment]
I think this is a duplicate of #160, so I'll close it till i can try the most current build
