### ISSUE TITLE
MacOS version crash after done scanning

### ISSUE THREAD

**Issue by caohaison123** [0x90d/videoduplicatefinder#206]
**Environment**
 - Macbook Air M1
 - OS: MacOS Big Sur 11.6

**Description**
HI, I'm a complete beginner in coding/programming so please bear with my very basic, non-techy way of describing issues lol. 

So when I try to scan my video files for duplicates, the program seems to run just fine, but when it's time to display the results, it always immediately crash and throw these errors in the Terminal (see below).

 I've looked through it and from what I can discern, the 'libgdiplus' thing is the one causing problems. Of course, I've followed the guide and install everything as instructed (ffmpeg, ffprobe, homebrew, and eventually mono-libgdiplus). I've tried restarting and reinstalling, replacing different versions of ffmpeg, reinstalling brew, libgdiplus thing, etc. Doesn't work.

One thing to note, when I go into the settings and check off "Generate Preview Images", it doesn't crash and I can just use it like normal, but that wouldn't be very wise considering I won't even know what I'm deleting. 

Any suggestions on what else I can do to make it work? I've tried running it in a Windows VM and the thing works beautifully but takes forever and I can't delete directly from the app itself, so I'd love to fix this issue and run it natively on macOS. 

**Error Code**
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 1): image not found
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at VDF.Core.ScanEngine.<RetrieveThumbnails>b__57_1(DuplicateItem entry, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.RetrieveThumbnails()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(IntPtr this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 3645
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 116
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 148
   at VDF.GUI.Program.Main(String[] args)
zsh: abort

**Comment by 0x90d** [comment]
Unfortunately I don't have a Mac, only a virtual machine running MacOS Catalina and following the instructions VDF works fine. Like you said, it's caused by libgdiplus not found. Please check out this link: https://docs.microsoft.com/en-us/dotnet/core/install/macos and this https://gist.github.com/mtolly/384dbe51f4a78d6d2818. If you using the "native fffmpeg binding" please uncheck in settings and try again.

**Comment by 0x90d** [comment]
@caohaison123 I've dropped libgidplus dependency. Please try out the new version and let me know if this fixed your problem thanks.
