### ISSUE TITLE
Error message at the end of the 100% same file scanning job

### ISSUE THREAD

**Issue by wowkkwow** [0x90d/videoduplicatefinder#223]
**Environment**
 - OS: windows 10 pro 21H1 19043.1165

**Describe the bug**

I have built the latest source with visual studio 2022 preview.
At the end of the 100% same scanning job error message pops up.

here is the error message and test log
![VDF_error](https://user-images.githubusercontent.com/43441443/135712867-8ff1d40d-1f2a-432f-8048-1fb39d19fc1c.png)

17:14:15 => Finished gathering and hashing in 00:03:49.7794210
17:14:15 => Save scanned files to disk (172,277 files).
17:14:16 => Scan for duplicates...
17:15:02 => Scanning for duplicates in 148,501 files
18:16:48 => Finished scanning for duplicates in 01:02:32.4590886
18:16:48 => Highlighting best results...
18:16:48 => Scan done.
18:16:48 => Save scanned files to disk (172,277 files).
18:26:00 => ERROR: Failed to retrieve thumbnail from: xxxxx
FFmpeg exited with: 69
18:27:05 => ERROR: Failed to retrieve thumbnail from: xxxxx 
FFmpeg exited with: 69
18:34:32 => ERROR: Failed to retrieve thumbnail from: xxxxx 
FFmpeg exited with: 69
18:36:08 => ERROR: Failed to retrieve thumbnail from: xxxxx 
FFmpeg exited with: 69
18:41:15 => ERROR: Failed to retrieve thumbnail from: xxxxx
FFmpeg exited with: 69
18:41:59 => ERROR: Failed to retrieve thumbnail from: xxxxx

18:42:32 => Exporting scan results has failed because of System.ArgumentException: .NET number values such as positive and negative infinity cannot be written as valid JSON.
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueNotSupported()
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Single value)
   at System.Text.Json.Serialization.Converters.SingleConverter.Write(Utf8JsonWriter writer, Single value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at VDF.GUI.ViewModels.MainWindowVM.ExportScanResultsIncludingThumbnails(String path) in C:\Users\Gold4K\Source\Repos\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 698
-------------------
 and my setting
![VDF_setting](https://user-images.githubusercontent.com/43441443/135713061-851112ad-155b-4aa8-80e1-e715baf20aa4.png)

------------------------------------

many of  file list (not 100% same ) in one group and other 100% same groups show in the result list.

**Expected behavior**
I want no error message and correct % result list.

**Comment by wowkkwow** [comment]
![image](https://user-images.githubusercontent.com/43441443/135774356-4641f7d1-dd0a-422e-9730-6cc38957d19b.png)
The one group similarity NaN shows

**Comment by 0x90d** [comment]
Does the group contains horizontally flipped videos?

**Comment by wowkkwow** [comment]
No horizontally flipped videos and the videos on this NaN group none valid duplicates.

**Comment by 0x90d** [comment]
Always the same videos which have NaN? If so, any chance you can give me an example video because I'm unable to reproduce this

**Comment by Maltragor** [comment]
The most probable reason for a NaN is probably the division "0/0".

Spontaneously, I noticed the places:
https://github.com/0x90d/videoduplicatefinder/blob/7f1a6493946a2f85a2ce68909e14c55f0b9594b8/VDF.Core/ScanEngine.cs#L267
However, this seems very unlikely to me, since for this positionList.Count would have to be zero.

Another place is https://github.com/0x90d/videoduplicatefinder/blob/7f1a6493946a2f85a2ce68909e14c55f0b9594b8/VDF.Core/Utils/GrayBytesUtils.cs#L79
Complete function:
https://github.com/0x90d/videoduplicatefinder/blob/7f1a6493946a2f85a2ce68909e14c55f0b9594b8/VDF.Core/Utils/GrayBytesUtils.cs#L64-L80
`diff` and `counter` are initialized with zero. The loop skips changing this variables if the pixels are to dark/bright. So if this would happen for all pixels of a grayscale image we get a NaN.


@wowkkwow: 
Pleas disable "Ignore Black Pixels" and "Ignore White Pixels" and check if the error disappears with it.
Are there more or less completely black or white thumbnails included with the NaN duplicates?

**Comment by Maltragor** [comment]
And since a comparison with NaN always returns false, CheckIfDuplicate():

https://github.com/0x90d/videoduplicatefinder/blob/7f1a6493946a2f85a2ce68909e14c55f0b9594b8/VDF.Core/ScanEngine.cs#L261
would not recognize this as non similar.

If it is intended that PercentageDifferenceWithoutSpecificPixels() can also return NaN and this was correctly taken into account in the calling function in the variant before adding flipped detection - sorry, I hadn't thought of that case then.
`if (!(diff <= differenceLimit)) ` (+ a comment why inverse logic is used) would then handle the case properly.

**Comment by Maltragor** [comment]
Before flipped detection the corresponding comparison was inverted:
```c#
if (percent[j] <= percentageDifference) {
	duplicateCounter++;
}
else { break; }
```
But it would probably still be a question of whether the resulting outcome is desirable.
With the Ignore Black/White configuration, as soon as even one of the scenes viewed, depending on the number of thumbnails, is sufficiently dark or bright and thus returns NaN, the video would never be recognized as a duplicate.
Another realization would be that the NaN case is counted as a match (diff=0) (or falls back to comparing all pixels regardless of the threshold)
This would still allow the video to be detected as a duplicate.

**Comment by NixonUey** [comment]
I'm getting the same problem and it is caused when "Ignore Black Pixels" and/or "Ignore White Pixels" is on. Groups contain false positives because of dark (or light) video. Turn the "Ignore" options off and no error.

**Comment by Maltragor** [comment]
Basis for discussion and two further remarks:
https://github.com/0x90d/videoduplicatefinder/compare/7f1a6493946a2f85a2ce68909e14c55f0b9594b8...Maltragor:bugfix/NaN_SpecificPixels
