### ISSUE TITLE
Crashing when dealing with large amounts of files (but only on first attempt)

### ISSUE THREAD

**Issue by kattjevfel** [0x90d/videoduplicatefinder#310]
**Environment**
 - OS: Arch Linux

**Describe the bug**
When performing a scan on ~150k files (images option enabled), the application crashes:
```
katt@main ~ » /home/katt/build/videoduplicatefinder/build/VDF.GUI
Unhandled exception. System.AggregateException: One or more errors occurred. (The given key '0' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at VDF.Core.ScanEngine.CheckIfDuplicate(FileEntry entry, Dictionary`2 grayBytes, FileEntry compItem, Single& difference) in /home/katt/build/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 318
   at VDF.Core.ScanEngine.<>c__DisplayClass64_0.<ScanForDuplicates>b__0(Int32 i) in /home/katt/build/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 385
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at VDF.Core.ScanEngine.ScanForDuplicates()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.StartCompare() in /home/katt/build/videoduplicatefinder/VDF.Core/ScanEngine.cs:line 116
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at VDF.GUI.Program.Main(String[] args) in /home/katt/build/videoduplicatefinder/VDF.GUI/Program.cs:line 32
[1]    67607 IOT instruction (core dumped)  /home/katt/build/videoduplicatefinder/build/VDF.GUI
```

Re-launching the application and simply starting the scan again seems to work every single time. But issue returns next time I run it (with more changed files, related?)

**Expected behavior**
Application to not crash and finish the scan without me having to restart it.

**Additional details**
Compiled with dotnet 6.0.2.sdk102 with same options as github workflow.

**Comment by Shituation** [comment]
+1, also disabled ffmpeg binding to test but was the same.
Do you have symbolic links on those folders? hardlinks?

**Comment by kattjevfel** [comment]
I have a bunch of hardlinks and symbolic links, yes. But we're talking maybe 100 files out of 150000.

**Comment by Shituation** [comment]
> I have a bunch of hardlinks and symbolic links, yes. But we're talking maybe 10 files out of 150000.

This app has horrible times dealing with symbolic links and hardlinks.
Apparently the problem is out of the scope of the developer said himself. Windows was blamed for the problem at first, they said it was because "the way windows manages hardlinks".

Let's see what the problem is this time. 

PS: I'm running windows and have the same problem.

**Comment by qarmin** [comment]
Can confirm on Ubuntu 22.04, also crash happens only when scanning for the first time

**Comment by qarmin** [comment]
Example file - [Icons.zip](https://github.com/0x90d/videoduplicatefinder/files/8749320/Icons.zip)

**Comment by Maltragor** [comment]
Regarding "up-for-grabs": I can explain what the problem is, but how exactly you want to fix it I leave to you. Because otherwise I would first have to understand why you introduced `entry.invalid` and when it needs to be updated. Because the problem is that entry.invalid is not updated every time it should be.

It happened aground c673e64b, when you when you introduced `entry.invalid` and changed `InvalidEntryForDuplicateCheck(FileEntry entry)`:  from `InvalidEntry(entry)` to `entry.invalid`.

First scan:
`GatherInfos()` is called 
-> `entry.invalid = InvalidEntry(entry);` but at that time no attempt was made to generate the grayBytes
-> grayBytes are generated at the end of the function. This can fail e.g. if the image is to dark -> EntryFlags.TooDark is set but `entry.invalid` keeps `false`.

Then `ScanForDuplicates()` is called and `InvalidEntryForDuplicateCheck(entry)`.
Since `InvalidEntryForDuplicateCheck()` only checks `entry.invalid` the `EntryFlags.TooDark` is lost. So an entry without grayBytes is added to the scanList and later on will cause the exception.
