### ISSUE TITLE
Core dump with build downloaded 2022.XII.11 under linux

### ISSUE THREAD

**Issue by gregoirefavre** [0x90d/videoduplicatefinder#359]
**Environment**
 - OS: Linux (archlinux)

**Describe the bug**
After the start of the scan I got a core dump : 

./VDF.GUI
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.ScanEngine.<GatherInfos>b__62_0(FileEntry entry, CancellationToken token)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.GatherInfos()
   at VDF.Core.ScanEngine.StartSearch()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at VDF.GUI.Program.Main(String[] args) in /home/runner/work/videoduplicatefinder/videoduplicatefinder/VDF.GUI/Program.cs:line 32
Aborted (core dumped)

**Expected behavior**
A run without core dump. Also I discovered that running "./VDF.GUI &" only works if J fg it (but that's not a real problem once I know it).

**Comment by 0x90d** [comment]
I cannot reproduce this. Can you? Then please run VDF debugged using Visual Studio Code, when the exception occurs it should show us what exactly is null.
