### ISSUE TITLE
File in use by VDF.GUI

### ISSUE THREAD

**Issue by chchia** [0x90d/videoduplicatefinder#397]
**Environment**
 - OS: Windows 11

**Describe the bug**
in some situation, the file cannot be delete, trying to delete by Open in folder manually, it will show
![image](https://user-images.githubusercontent.com/1291771/217702805-7a437df6-123c-4dc6-b531-b9d196b6ace6.png)

**Expected behavior**
VDF.GUI should not occupied the files.

**Comment by 0x90d** [comment]
What are these "situations"? More information including steps to reproduce please.

**Comment by chchia** [comment]
very random, i do not know how to reproduce, but the log section showing

`10:30:22 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4', reason: The process cannot access the file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4' because it is being used by another process., Stacktrace    at System.IO.FileSystem.DeleteFile(String fullPath)
   at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 905`

**Comment by chchia** [comment]
and i do not have this folder in D:

D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs

**Comment by chchia** [comment]
more log found
`10:25:40 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-29-03.mp4', reason: Object reference not set to an instance of an object., Stacktrace    at Avalonia.VisualTree.VisualExtensions.GetVisualAt(IVisual visual, Point p, Func`2 filter) in /_/src/Avalonia.Base/VisualTree/VisualExtensions.cs:line 246
   at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p) in /_/src/Avalonia.Base/Input/InputExtensions.cs:line 40
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 536
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 727
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at VDF.Core.Utils.FileUtils.SHFileOperation(SHFILEOPSTRUCT& FileOp)
   at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 889
10:25:42 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4', reason: SHFileOperation returned: 20, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 903
10:25:50 => Save scanned files to disk (102,334 files).
10:29:37 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-29-03.mp4', reason: Object reference not set to an instance of an object., Stacktrace    at Avalonia.VisualTree.VisualExtensions.GetVisualAt(IVisual visual, Point p, Func`2 filter) in /_/src/Avalonia.Base/VisualTree/VisualExtensions.cs:line 246
   at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p) in /_/src/Avalonia.Base/Input/InputExtensions.cs:line 40
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 536
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 727
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at VDF.Core.Utils.FileUtils.SHFileOperation(SHFILEOPSTRUCT& FileOp)
   at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 889
10:29:38 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4', reason: SHFileOperation returned: 20, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 903
10:29:38 => Save scanned files to disk (102,334 files).
10:30:22 => Failed to delete file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4', reason: The process cannot access the file 'Z:\media\Animals\telegram\video_2023-02-07_13-26-06.mp4' because it is being used by another process., Stacktrace    at System.IO.FileSystem.DeleteFile(String fullPath)
   at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 905`

**Comment by 0x90d** [comment]
> and i do not have this folder in D:
> 

That is the path of the building machine, ignore that. Is that the LATEST version here from Github? Please check this twice. If not, please download and reproduce and then show me the log again.

Also see if disabling the thumbnail generation makes a difference. That would be the only thing where VDF could lock the file I think.

**Comment by chchia** [comment]
i was using the latest daily built.

**Comment by 0x90d** [comment]
That is not possible as the line numbers are incorrect. Also what is with the thumbnail generation I've mentioned?

**Comment by chchia** [comment]
downloaded daily dev build yesterday and let it run overnight, and tried to delete the duplicate just now and i got

```04:28:31 => Failed to delete file 'Z:\media\5.mp4', reason: Object reference not set to an instance of an object., Stacktrace    at Avalonia.VisualTree.VisualExtensions.GetVisualAt(IVisual visual, Point p, Func`2 filter) in /_/src/Avalonia.Base/VisualTree/VisualExtensions.cs:line 246
   at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p) in /_/src/Avalonia.Base/Input/InputExtensions.cs:line 40
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 536
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 727
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at VDF.Core.Utils.FileUtils.SHFileOperation(SHFILEOPSTRUCT& FileOp)
   at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 889
04:28:33 => Failed to delete file 'Z:\media\01.mp4', reason: SHFileOperation returned: 20, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 903
04:28:34 => Failed to delete file 'Z:\media\Animals\video_2022-02-11_22-18-10.mp4', reason: SHFileOperation returned: 20, Stacktrace    at VDF.GUI.ViewModels.MainWindowVM.DeleteInternal(Boolean fromDisk, Boolean blackList, Boolean createSymbolLinksInstead, Boolean permanently) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\ViewModels\MainWindowVM.cs:line 903```

tried with thumbnail generation disabled.

**Comment by 0x90d** [comment]
Are there any ffmpeg / ffprobe tasks running when this occurs?

**Comment by chchia** [comment]
i did check the Task Manager, but i dont see any ffmpeg/ffprobe under VDF.GUI

**Comment by 0x90d** [comment]
I honestly don't know what else of VDF would block that file and I cannot reproduce the problem either. It appears you're the only one where it happens. Please try and figure out steps that can be reproduced so I can see whats going on.

**Comment by chchia** [comment]
i dont know how to reproduce, this seems very random, some time the same file become able to delete after the next scan.

another possible is my Z: drive is a remote samba folder hosted inside a Synology. however previously (a month ago maybe) i dont have this problem to delete, this problem was just start to appear about a month ago.

**Comment by 0x90d** [comment]
Can you make a screenshot of your whole scan settings please (you can remove scan directories)?

**Comment by chchia** [comment]
sure!

![image](https://user-images.githubusercontent.com/1291771/220651566-d5a7de5a-3b41-42e6-9ead-2390339ba170.png)

![image](https://user-images.githubusercontent.com/1291771/220651731-52f643c8-e574-4a82-9df3-a81918cad63d.png)

![image](https://user-images.githubusercontent.com/1291771/220651836-7521443f-6011-4a8b-9f19-3938ce2b848e.png)

**Comment by 0x90d** [comment]
As you said it happened recently I thought you may use hardlink detection. There was also an update on Avalonia. I'll leave this issue open for a while maybe someone else can provide more information.

**Comment by 0x90d** [comment]
Looks like no else can provide information or it doesn't happen for anyone else.
