### ISSUE TITLE
[Bug]: Uncaught System.IO.FileNotFoundException in VDF.Core.ScanEngine.InvalidEntry

### ISSUE THREAD

**Issue by GuillaumeBailey** [0x90d/videoduplicatefinder#452]
## Environment
 - OS: MacOS

## Describe the bug
 - Imported db & settings from a previous version of VideoDuplicateFinder
 - I have "Scan against non-existing files" set.
 - During a scan, application crashed with:
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Volumes/share/some.mp4'.
File name: '/Volumes/share/some.mp4'
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory)
   at VDF.Core.ScanEngine.InvalidEntry(FileEntry entry)
   at VDF.Core.ScanEngine.<GatherInfos>b__62_0(FileEntry entry, CancellationToken token)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.GatherInfos() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 282
   at VDF.Core.ScanEngine.StartSearch() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 98
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4586
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at VDF.GUI.Program.Main(String[] args) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\Program.cs:line 30
Abort trap: 6
```

```
16:35:14 => Found previously scanned files, importing...
16:35:14 => Previously scanned files imported. 10,337 files in 00:00:00.1659215
16:38:30 => Building file list...
16:38:30 => Found previously scanned files, importing...
16:38:30 => Previously scanned files imported. 10,337 files in 00:00:00.0920829
16:46:49 => Files in database: 22,531 (12,194 files added)
16:46:49 => Finished building file list in 00:08:18.7076413
16:46:49 => Gathering media info and buildings hashes...
```

```
{
  "Includes": [
    "/Volumes/share/"
  ],
  "Blacklists": [],
  "LastCustomSelectExpression": "arg.ItemInfo.IsBestSize",
  "IgnoreReadOnlyFolders": false,
  "ExcludeHardLinks": false,
  "IgnoreReparsePoints": true,
  "IgnoreBlackPixels": true,
  "IgnoreWhitePixels": true,
  "MaxDegreeOfParallelism": -1,
  "HardwareAccelerationMode": 1,
  "CompareHorizontallyFlipped": false,
  "IncludeSubDirectories": true,
  "IncludeImages": false,
  "GeneratePreviewThumbnails": true,
  "ExtendedFFToolsLogging": false,
  "AlwaysRetryFailedSampling": true,
  "UseNativeFfmpegBinding": false,
  "CustomFFArguments": "",
  "BackupAfterListChanged": true,
  "AskToSaveResultsOnExit": true,
  "IncludeNonExistingFiles": true,
  "ScanAgainstEntireDatabase": false,
  "Percent": 85,
  "PercentDurationDifference": 0,
  "Thumbnails": 5,
  "CustomCommands": {
    "OpenItemInFolder": "",
    "OpenMultipleInFolder": "",
    "OpenItem": "",
    "OpenMultiple": ""
  },
  "CustomDatabaseFolder": "",
  "UseMica": true,
  "DarkMode": true,
  "ShowThumbnailColumn": true,
  "ShowPathColumn": true,
  "ShowDurationColumn": true,
  "ShowFormatColumn": true,
  "ShowAudioColumn": true,
  "ShowSimilarityColumn": true,
  "FilterByFilePathContains": false,
  "FilePathContainsTexts": [],
  "FilterByFilePathNotContains": false,
  "FilePathNotContainsTexts": [],
  "FilterByFileSize": false,
  "MaximumFileSize": 999999999,
  "MinimumFileSize": 0,
  "Changing": {},
  "Changed": {},
  "ThrownExceptions": {}
}
```
## Snapshots
Optionally, include snapshots showing the issue.

**Comment by GuillaumeBailey** [comment]
https://github.com/0x90d/videoduplicatefinder/pull/453
