### ISSUE TITLE
[Bug]: Crash during scan (Windows)

### ISSUE THREAD

**Issue by Chrisch3n** [0x90d/videoduplicatefinder#541]
## Environment
 - OS: Windows

## Describe the bug

The App/GUI keeps crashing during scans after a while (After enumerating files and at least a few minutes to hours into the actual scan).
I changed the Parallelism setting because, I thought, that that might cause the crash - to no avail.

Crash with Parallelism Parameter: 1 (I had the feeling it ran longer, but it might be the same number of files/ same point as with Parallelism "-1" and took just longer due to the fewer threads used)
``
Application: VDF.GUI.exe
CoreCLR Version: 7.0.2024.26716
.NET Version: 7.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.ScanEngine.<GatherInfos>b__62_0(FileEntry entry, CancellationToken token)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.GatherInfos() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 311
   at VDF.Core.ScanEngine.StartSearch() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 98
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at VDF.GUI.Program.Main(String[] args) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\Program.cs:line 30
``

Crash with Parallelism Parameter: -1 (seems to be the same error)
``
Application: VDF.GUI.exe
CoreCLR Version: 7.0.2024.26716
.NET Version: 7.0.20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at VDF.Core.ScanEngine.<GatherInfos>b__62_0(FileEntry entry, CancellationToken token)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.GatherInfos() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 311
   at VDF.Core.ScanEngine.StartSearch() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 98
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at VDF.GUI.Program.Main(String[] args) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\Program.cs:line 30
``

**Comment by 0x90d** [comment]
I think the problem is fixed in one of the last updates. Can you try the latest version?
