### ISSUE TITLE
[Bug]: App Crash!!

### ISSUE THREAD

**Issue by Topspap** [0x90d/videoduplicatefinder#550]
## Environment:
OS: Windows 11

## Describe the bug:
While scanning for duplicate videos, the app crashes. 

## Error Message from Event Viewer:
```
Application: VDF.GUI.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Text.EncoderFallbackException: Unable to translate Unicode character \\uDC00 at index 191 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.Encoder.GetBytes(ReadOnlySpan`1 chars, Span`1 bytes, Boolean flush)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at VDF.Core.Utils.Logger.Info(String text) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\Utils\Logger.cs:line 33
   at VDF.Core.FFTools.FFProbeEngine.GetMediaInfo(String file, Boolean extendedLogging) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\FFTools\FFProbeEngine.cs:line 83
   at VDF.Core.ScanEngine.<GatherInfos>b__62_0(FileEntry entry, CancellationToken token)
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at VDF.Core.ScanEngine.GatherInfos() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 284
   at VDF.Core.ScanEngine.StartSearch() in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.Core\ScanEngine.cs:line 98
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 276
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at VDF.GUI.Program.Main(String[] args) in D:\a\videoduplicatefinder\videoduplicatefinder\VDF.GUI\Program.cs:line 30
```

## After long investigation, this is what I understood (with a workaround solution):
First, when running the scan again, the app crashed with similar error message but this time: `Unable to translate Unicode character \\uDCA5 at index 178`
So I started running the scan on small groups of files to find out which file was causing the error. 
It was a group of files with some weird characters in their names, like "un-unicode" or "non-ASCII" I'm not sure as I got confused with the world of characters and their type... anyway.
When I renamed the files and removed these weird characters, the problem disappeared, and everything worked fine.

• Another info: these exact files were unplayable with "VLC" and when these characters were removed, it worked perfectly.

Here is the weird character and a screenshot of them. As I noticed when I copy and paste them here, they change as if they are being decoded in a different way!! (Part of my cofusion of these characters)
```
ﱱ�0150.mp4
ﱱ�ﱱ�ﱱ�ﱱ�ﱱ�ﱱ�ﱱ�ﱱ�ﱱ�0060.mp4
ﱛ� ﲳ�0024.mp4
ﱛ�0004.mp4
ﱛ�0036.mp4
ﱛ�0078.mp4
ﱛ�0108.mp4
ﰱ�‍♂️0231.mp4
ﰺ�0164.mp4
ﯢ�‍♂️ ﲁ�ﯗ�ﱖ�0200.mp4
ﱝ� c0208.mp4
ﯮ�0009.mp4
ﯵ�‍♂️0111.mp4
﯏�ﱛ�0002.mp4
```
![image](https://github.com/user-attachments/assets/ba1800fa-8c68-4c05-8ce7-957e09744990)

## My Question:
• Is there a way to find all files with these characters in their names? or any other characters that may cause the same error? 
• Is there a way to automate the renaming of these files? and replace these characters with their closest in "UTF-8" instead of removing them?
• What are these characters called?

**Comment by 0x90d** [comment]
This is not really a bug in VDF. The filenames are simply invalid and you would have to rename them. I don't know a way to search for explicit these files
