### ISSUE TITLE
exception report for every image file

### ISSUE THREAD

**Issue by 2020pt** [0x90d/videoduplicatefinder#64]
**Environment**
 - OS: Linux Mint

**Describe the bug**
Scans folder but when 'Include Images' is selected every image file just generates an error in the log:
```
13:19:28	Exception, file: /home/mint/Videos/DSC002588.jpg, reason: The type initializer for 'Gdip' threw an exception., stacktrace    at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetImageAsBitmaps(VideoFileEntry videoFile, Int32 count) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 390

```
**Expected behavior**
No error

**Comment by 0x90d** [comment]
Do you have libgdiplus installed? https://github.com/0x90d/videoduplicatefinder#linux-user

**Comment by 2020pt** [comment]
yes, pretty sure I did - as mentioned in other thread done a rebuild of my system so cant check what I had at the time now

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
