### ISSUE TITLE
"Parameter is not valid" when scanning for duplicates

### ISSUE THREAD

**Issue by yetipenguin** [0x90d/videoduplicatefinder#92]
**Environment**
 - OS: Linux - Ubuntu LInux 18.04.4 LTS 64-Bit. WindowMaker 0.95.9
- VDF version 2.0.7

**Describe the bug**
1. Start using "LANG=C_ALL ./VideoDuplicateFinderLinux"
2. Add a folder with multiple video files.
3. Click on "Start"

**Expected behavior**
VDF scans all files in the folder and reports possible duplicates.

**Actual behaviour**
The files get listet, but no duplicate is reported. In the log are some error messages about an invalid parameter (replaced username and file names):

> 21:08:24	OS: Linux 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020
21:08:42	Building file list...
21:08:42	Found previously scanned files, importing...
21:08:42	Previously scanned files imported. 612 files in 00:00:00.3348024
21:08:42	Finished building file list in 00:00:00.0015847
21:08:42	Start scan
21:08:42	Thumbnails finished in: 00:00:00.0008803, processed files: 0
21:08:43	Save scanned files to disk (612 files).
21:08:43	Scan done
21:08:43	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitle 2 - SomeMovieTitles - SomeString edition (de,1986) cd2.avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieSubTitel 2 - english.avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitle 4 - SomeMovieTitle resurrection - SomeString edition (de,1997).avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitle 2 - SomeMovieTitles - SomeString edition (de,1986) cd1.avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:43	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitle 1 - SomeString edition (de,1979).avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitle 3 - SomeMovieTitle3 - SomeString edition (de,1992).avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Duplicates check finished in: 00:00:00.0171775
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieSubTitel 1 - english.avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitels.Vs.SomeMovieSubTitel.2.DVDRip.Line.Dubbed.German.avi, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311
21:08:43	Thumbnails finished in: 00:00:00.3359669, processed files: 9
21:08:42	Exception, file: /home/username/movies/SomeMovieTitel - SomeMovieSubTitel alle/SomeMovieTitels.vs.SomeMovieSubTitel.1.mpg, reason: Parameter is not valid., stacktrace    at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at DuplicateFinderEngine.ScanEngine.GetVideoThumbnail(DuplicateItem videoFile, List`1 positions) in C:\Users\User\Documents\Visual Studio 2017\Projects\DuplicateFinder\DuplicateFinderEngine\ScanEngine.cs:line 311

**Comment by 0x90d** [comment]
Can you try this with 2.0.8 and let me know if this still happens?

**Comment by yetipenguin** [comment]
@0x90d unfortunately not. With 2.0.8 I even can not start the program:

> ./VideoDuplicateFinderLinux
Unhandled exception. Avalonia.Markup.Xaml.XamlLoadException: No precompiled XAML found for VideoDuplicateFinderLinux.App, make sure to specify x:Class and include your XAML file as AvaloniaResource
   at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
   at VideoDuplicateFinderLinux.App.Initialize() in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\App.xaml.cs:line 11
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at VideoDuplicateFinderLinux.Program.Main(String[] args) in C:\Users\User\Desktop\DuplicateFinder\VideoDuplicateFinderLinux\Program.cs:line 7
Abgebrochen (Speicherabzug geschrieben)

**Comment by yetipenguin** [comment]
Dear @0x90d any updates on this issue? How can I help to solve this?

**Comment by 0x90d** [comment]
Closing because this refers to outdated VDF Version 2
